p 'Create admin zeljko, password zeljko123, and many racers'

# zeljko is an admin
@zm = User.create! email: 'zeljko@z-ware.fi',
             password: 'zeljko123',
             password_confirmation: 'zeljko123',
             admin: true

# Kata is not an admin, but has the owner of almost all the events
# except ROI cross
@kp = User.create! email: 'kata@iloisettassut.fi',
             password: 'zeljko123',
             password_confirmation: 'zeljko123',
             name: 'Katariina Puolakanaho',
             nationality: :finland

# Toni is not an admin, but is an owner of two races:
# ROI Cross (alone) and EC 2014 Rautavaara (with kp)
@tp = User.create! email: 't.j.parkkinen@gmail.com',
             password: 'zeljko123',
             password_confirmation: 'zeljko123',
             name: 'Toni Parkkinen',
             nationality: :finland

@amf ||= User.create! email: 'antti.mäkiaho@example.com',
                  password: 'Antti1234567',
                  password_confirmation: 'Antti1234567',
                  name: 'Antti Mäkiaho',
                  nationality: :finland
@itp ||= User.create! email: 'igor.tracz@example.com',
                  password: 'Igor1234567',
                  password_confirmation: 'Igor1234567',
                  name: 'Igor Tracz',
                  nationality: :poland
@ehf ||= User.create! email: 'essi.hytönen@example.com',
                  password: 'Essi1234567',
                  password_confirmation: 'Essi1234567',
                  name: 'Essi Hytönen',
                  nationality: :finland
@ebs ||= User.create! email: 'elin.björk@example.com',
                  password: 'Elin1234567',
                  password_confirmation: 'Elin1234567',
                  name: 'Elin Björk',
                  nationality: :sweden
@rvc ||= User.create! email: 'renata.válková@example.com',
                  password: 'Renata1234567',
                  password_confirmation: 'Renata1234567',
                  name: 'Renata Válková',
                  nationality: :czechrepublic
@arp ||= User.create! email: 'agnieszka.rychwalska@example.com',
                  password: 'Agnieszka1234567',
                  password_confirmation: 'Agnieszka1234567',
                  name: 'Agnieszka Rychwalska',
                  nationality: :poland
@mhs ||= User.create! email: 'mikael.högberg@example.com',
                  password: 'Mikael1234567',
                  password_confirmation: 'Mikael1234567',
                  name: 'Mikael Högberg',
                  nationality: :sweden
@css ||= User.create! email: 'catarina.södersten@example.com',
                  password: 'Catarina1234567',
                  password_confirmation: 'Catarina1234567',
                  name: 'Catarina Södersten',
                  nationality: :sweden
@hhg ||= User.create! email: 'herbert.hiermeier@example.com',
                  password: 'Herbert1234567',
                  password_confirmation: 'Herbert1234567',
                  name: 'Herbert Hiermeier',
                  nationality: :germany
@kkn ||= User.create! email: 'krisztianroland.kiss@example.com',
                  password: 'KrisztianRoland1234567',
                  password_confirmation: 'KrisztianRoland1234567',
                  name: 'KrisztianRoland Kiss',
                  nationality: :norway
@sgs ||= User.create! email: 'sussie.grönberg@example.com',
                  password: 'Sussie1234567',
                  password_confirmation: 'Sussie1234567',
                  name: 'Sussie Grönberg',
                  nationality: :sweden
@hlf ||= User.create! email: 'heta.lehtomäki@example.com',
                  password: 'Heta1234567',
                  password_confirmation: 'Heta1234567',
                  name: 'Heta Lehtomäki',
                  nationality: :finland
@lpp ||= User.create! email: 'lukasz.paczynski@example.com',
                  password: 'Lukasz1234567',
                  password_confirmation: 'Lukasz1234567',
                  name: 'Lukasz Paczynski',
                  nationality: :poland
@dnc ||= User.create! email: 'dagmar.nesnerová@example.com',
                  password: 'Dagmar1234567',
                  password_confirmation: 'Dagmar1234567',
                  name: 'Dagmar Nesnerová',
                  nationality: :czechrepublic
@apf ||= User.create! email: 'anu.parikka@example.com',
                  password: 'Anu1234567',
                  password_confirmation: 'Anu1234567',
                  name: 'Anu Parikka',
                  nationality: :finland
@sbf ||= User.create! email: 'susanna.bürkland@example.com',
                  password: 'Susanna1234567',
                  password_confirmation: 'Susanna1234567',
                  name: 'Susanna Bürkland',
                  nationality: :finland
@mkl ||= User.create! email: 'martins.kristons@example.com',
                  password: 'Martins1234567',
                  password_confirmation: 'Martins1234567',
                  name: 'Martins Kristons',
                  nationality: :latvia
@ahf ||= User.create! email: 'alain.hercher@example.com',
                  password: 'Alain1234567',
                  password_confirmation: 'Alain1234567',
                  name: 'Alain Hercher',
                  nationality: :france
@tnf ||= User.create! email: 'tuomas.notko@example.com',
                  password: 'Tuomas1234567',
                  password_confirmation: 'Tuomas1234567',
                  name: 'Tuomas Notko',
                  nationality: :finland
@por ||= User.create! email: 'pavel.otbetkin@example.com',
                  password: 'Pavel1234567',
                  password_confirmation: 'Pavel1234567',
                  name: 'Pavel Otbetkin',
                  nationality: :russia
@spc ||= User.create! email: 'slavomir.pavlik@example.com',
                  password: 'Slavomir1234567',
                  password_confirmation: 'Slavomir1234567',
                  name: 'Slavomir Pavlik',
                  nationality: :czechrepublic
@jhn ||= User.create! email: 'julieboysen.hillestad@example.com',
                  password: 'JulieBoysen1234567',
                  password_confirmation: 'JulieBoysen1234567',
                  name: 'JulieBoysen Hillestad',
                  nationality: :norway
@acf ||= User.create! email: 'axel.coste@example.com',
                  password: 'Axel1234567',
                  password_confirmation: 'Axel1234567',
                  name: 'Axel Coste',
                  nationality: :france
@vlf ||= User.create! email: 'vilma.laitinen@example.com',
                  password: 'Vilma1234567',
                  password_confirmation: 'Vilma1234567',
                  name: 'Vilma Laitinen',
                  nationality: :finland
@khf ||= User.create! email: 'kimmo.hytönen@example.com',
                  password: 'Kimmo1234567',
                  password_confirmation: 'Kimmo1234567',
                  name: 'Kimmo Hytönen',
                  nationality: :finland
@cts ||= User.create! email: 'conny.töyrä@example.com',
                  password: 'Conny1234567',
                  password_confirmation: 'Conny1234567',
                  name: 'Conny Töyrä',
                  nationality: :sweden
@tkf ||= User.create! email: 'teemu.kaivola@example.com',
                  password: 'Teemu1234567',
                  password_confirmation: 'Teemu1234567',
                  name: 'Teemu Kaivola',
                  nationality: :finland
@ton ||= User.create! email: 'trine.olsen@example.com',
                  password: 'Trine1234567',
                  password_confirmation: 'Trine1234567',
                  name: 'Trine Olsen',
                  nationality: :norway
@rkf ||= User.create! email: 'riitta.kempe@example.com',
                  password: 'Riitta1234567',
                  password_confirmation: 'Riitta1234567',
                  name: 'Riitta Kempe',
                  nationality: :finland
@vlf2 ||= User.create! email: 'vesa-pekka.lehtomäki@example.com',
                  password: 'Vesa-Pekka1234567',
                  password_confirmation: 'Vesa-Pekka1234567',
                  name: 'Vesa-Pekka Lehtomäki',
                  nationality: :finland
@jtc ||= User.create! email: 'jirí.trnka@example.com',
                  password: 'Jirí1234567',
                  password_confirmation: 'Jirí1234567',
                  name: 'Jirí Trnka',
                  nationality: :czechrepublic
@jkf ||= User.create! email: 'jenni.kreivi@example.com',
                  password: 'Jenni1234567',
                  password_confirmation: 'Jenni1234567',
                  name: 'Jenni Kreivi',
                  nationality: :finland
@idl ||= User.create! email: 'indre.daujotiene@example.com',
                  password: 'Indre1234567',
                  password_confirmation: 'Indre1234567',
                  name: 'Indre Daujotiene',
                  nationality: :lithuania
@mbg ||= User.create! email: 'michael.beck@example.com',
                  password: 'Michael1234567',
                  password_confirmation: 'Michael1234567',
                  name: 'Michael Beck',
                  nationality: :germany
@mcs ||= User.create! email: 'montse.claverol@example.com',
                  password: 'Montse1234567',
                  password_confirmation: 'Montse1234567',
                  name: 'Montse Claverol',
                  nationality: :spain
@amf ||= User.create! email: 'antti.mäkiaho@example.com',
                  password: 'Antti1234567',
                  password_confirmation: 'Antti1234567',
                  name: 'Antti Mäkiaho',
                  nationality: :finland
@mcc ||= User.create! email: 'michael.chovanec@example.com',
                  password: 'Michael1234567',
                  password_confirmation: 'Michael1234567',
                  name: 'Michael Chovanec',
                  nationality: :czechrepublic
@abp ||= User.create! email: 'anna.bajer@example.com',
                  password: 'Anna1234567',
                  password_confirmation: 'Anna1234567',
                  name: 'Anna Bajer',
                  nationality: :poland
@atf ||= User.create! email: 'anttoni.tolvi@example.com',
                  password: 'Anttoni1234567',
                  password_confirmation: 'Anttoni1234567',
                  name: 'Anttoni Tolvi',
                  nationality: :finland
@lpp ||= User.create! email: 'lukasz.paczynski@example.com',
                  password: 'Lukasz1234567',
                  password_confirmation: 'Lukasz1234567',
                  name: 'Lukasz Paczynski',
                  nationality: :poland
@phf ||= User.create! email: 'pasi.heinonen@example.com',
                  password: 'Pasi1234567',
                  password_confirmation: 'Pasi1234567',
                  name: 'Pasi Heinonen',
                  nationality: :finland
@rsf ||= User.create! email: 'riku.setälä@example.com',
                  password: 'Riku1234567',
                  password_confirmation: 'Riku1234567',
                  name: 'Riku Setälä',
                  nationality: :finland
@akg ||= User.create! email: 'alexandra.kathan@example.com',
                  password: 'Alexandra1234567',
                  password_confirmation: 'Alexandra1234567',
                  name: 'Alexandra Kathan',
                  nationality: :germany
@cws ||= User.create! email: 'carl-johan.waller@example.com',
                  password: 'Carl-Johan1234567',
                  password_confirmation: 'Carl-Johan1234567',
                  name: 'Carl-Johan Waller',
                  nationality: :sweden
@hhg ||= User.create! email: 'herbert.hiermeier@example.com',
                  password: 'Herbert1234567',
                  password_confirmation: 'Herbert1234567',
                  name: 'Herbert Hiermeier',
                  nationality: :germany
@mtg ||= User.create! email: 'michael.tetzner@example.com',
                  password: 'Michael1234567',
                  password_confirmation: 'Michael1234567',
                  name: 'Michael Tetzner',
                  nationality: :germany
@vhf ||= User.create! email: 'ville.halme@example.com',
                  password: 'Ville1234567',
                  password_confirmation: 'Ville1234567',
                  name: 'Ville Halme',
                  nationality: :finland
@egl ||= User.create! email: 'eduard.grobinsch@example.com',
                  password: 'Eduard1234567',
                  password_confirmation: 'Eduard1234567',
                  name: 'Eduard Grobinsch',
                  nationality: :latvia
@svh ||= User.create! email: 'sophie.verla@example.com',
                  password: 'Sophie1234567',
                  password_confirmation: 'Sophie1234567',
                  name: 'Sophie Verla',
                  nationality: :hungary
@mtp ||= User.create! email: 'maciej.tomaszewski@example.com',
                  password: 'Maciej1234567',
                  password_confirmation: 'Maciej1234567',
                  name: 'Maciej Tomaszewski',
                  nationality: :poland
@klf ||= User.create! email: 'kaisa.lehto@example.com',
                  password: 'Kaisa1234567',
                  password_confirmation: 'Kaisa1234567',
                  name: 'Kaisa Lehto',
                  nationality: :finland
@fhn ||= User.create! email: 'frode.haugan@example.com',
                  password: 'Frode1234567',
                  password_confirmation: 'Frode1234567',
                  name: 'Frode Haugan',
                  nationality: :norway
@amr ||= User.create! email: 'aleksandr.moskvichev@example.com',
                  password: 'Aleksandr1234567',
                  password_confirmation: 'Aleksandr1234567',
                  name: 'Aleksandr Moskvichev',
                  nationality: :russia
@jbn ||= User.create! email: 'jos.broers@example.com',
                  password: 'Jos1234567',
                  password_confirmation: 'Jos1234567',
                  name: 'Jos Broers',
                  nationality: :netherlands
@hin ||= User.create! email: 'hege.ingerigtsen@example.com',
                  password: 'Hege1234567',
                  password_confirmation: 'Hege1234567',
                  name: 'Hege Ingerigtsen',
                  nationality: :norway
@kzs ||= User.create! email: 'kurt.zwingli@example.com',
                  password: 'Kurt1234567',
                  password_confirmation: 'Kurt1234567',
                  name: 'Kurt Zwingli',
                  nationality: :switzerland
@mtg ||= User.create! email: 'michael.tetzner@example.com',
                  password: 'Michael1234567',
                  password_confirmation: 'Michael1234567',
                  name: 'Michael Tetzner',
                  nationality: :germany
@tsg ||= User.create! email: 'tamara.schlemmer@example.com',
                  password: 'Tamara1234567',
                  password_confirmation: 'Tamara1234567',
                  name: 'Tamara Schlemmer',
                  nationality: :germany
@alf ||= User.create! email: 'ari.laitinen@example.com',
                  password: 'Ari1234567',
                  password_confirmation: 'Ari1234567',
                  name: 'Ari Laitinen',
                  nationality: :finland
@ksg ||= User.create! email: 'klaus.starflinger@example.com',
                  password: 'Klaus1234567',
                  password_confirmation: 'Klaus1234567',
                  name: 'Klaus Starflinger',
                  nationality: :germany
@crs ||= User.create! email: 'cari.rörström@example.com',
                  password: 'Cari1234567',
                  password_confirmation: 'Cari1234567',
                  name: 'Cari Rörström',
                  nationality: :sweden
@rcf ||= User.create! email: 'remy.coster@example.com',
                  password: 'Remy1234567',
                  password_confirmation: 'Remy1234567',
                  name: 'Remy Coster',
                  nationality: :france
@ads ||= User.create! email: 'alister.dunlop@example.com',
                  password: 'Alister1234567',
                  password_confirmation: 'Alister1234567',
                  name: 'Alister Dunlop',
                  nationality: :scotland
@psf ||= User.create! email: 'panu.sipilä@example.com',
                  password: 'Panu1234567',
                  password_confirmation: 'Panu1234567',
                  name: 'Panu Sipilä',
                  nationality: :finland
@rrg ||= User.create! email: 'rudi.ropertz@example.com',
                  password: 'Rudi1234567',
                  password_confirmation: 'Rudi1234567',
                  name: 'Rudi Ropertz',
                  nationality: :germany
@ppc ||= User.create! email: 'pavel.pfeifer@example.com',
                  password: 'Pavel1234567',
                  password_confirmation: 'Pavel1234567',
                  name: 'Pavel Pfeifer',
                  nationality: :czechrepublic
@pkf ||= User.create! email: 'pauliina.kiiski@example.com',
                  password: 'Pauliina1234567',
                  password_confirmation: 'Pauliina1234567',
                  name: 'Pauliina Kiiski',
                  nationality: :finland
@asr ||= User.create! email: 'aleksandr.stoliarov@example.com',
                  password: 'Aleksandr1234567',
                  password_confirmation: 'Aleksandr1234567',
                  name: 'Aleksandr Stoliarov',
                  nationality: :russia
@mvc ||= User.create! email: 'martin.vrtel@example.com',
                  password: 'Martin1234567',
                  password_confirmation: 'Martin1234567',
                  name: 'Martin Vrtel',
                  nationality: :czechrepublic
@gbp ||= User.create! email: 'grzegorz.burzynski@example.com',
                  password: 'Grzegorz1234567',
                  password_confirmation: 'Grzegorz1234567',
                  name: 'Grzegorz Burzynski',
                  nationality: :poland
@hma ||= User.create! email: 'horst.maas@example.com',
                  password: 'Horst1234567',
                  password_confirmation: 'Horst1234567',
                  name: 'Horst Maas',
                  nationality: :austria
@jss ||= User.create! email: 'johan.sernheim@example.com',
                  password: 'Johan1234567',
                  password_confirmation: 'Johan1234567',
                  name: 'Johan Sernheim',
                  nationality: :sweden
@jef ||= User.create! email: 'joni.elomaa@example.com',
                  password: 'Joni1234567',
                  password_confirmation: 'Joni1234567',
                  name: 'Joni Elomaa',
                  nationality: :finland
@kkf ||= User.create! email: 'kati.kumpulainen@example.com',
                  password: 'Kati1234567',
                  password_confirmation: 'Kati1234567',
                  name: 'Kati Kumpulainen',
                  nationality: :finland
@slf ||= User.create! email: 'suvi.lahtinen@example.com',
                  password: 'Suvi1234567',
                  password_confirmation: 'Suvi1234567',
                  name: 'Suvi Lahtinen',
                  nationality: :finland
@gzc ||= User.create! email: 'gregor.zdenek@example.com',
                  password: 'Gregor1234567',
                  password_confirmation: 'Gregor1234567',
                  name: 'Gregor Zdenek',
                  nationality: :czechrepublic
@paf ||= User.create! email: 'pia.alpua@example.com',
                  password: 'Pia1234567',
                  password_confirmation: 'Pia1234567',
                  name: 'Pia Alpua',
                  nationality: :finland
##############################################################
#smr

@vjf ||= User.create! email: 'vesa-pekka.jurvelin@example.com',
                  password: 'vesa-pekka1234567',
                  password_confirmation: 'vesa-pekka1234567',
                  name: 'Vesa-Pekka Jurvelin',
                  club: 'rpkk',
                  nationality: :finland
@mnf ||= User.create! email: 'maija.nivala@example.com',
                  password: 'maija1234567',
                  password_confirmation: 'maija1234567',
                  name: 'Maija Nivala',
                  club: 'rpkk',
                  nationality: :finland
@snf ||= User.create! email: 'samuli.nissinen@example.com',
                  password: 'samuli1234567',
                  password_confirmation: 'samuli1234567',
                  name: 'Samuli Nissinen',
                  club: 'kpsh',
                  nationality: :finland
@mtf ||= User.create! email: 'marika.tiiperi@example.com',
                  password: 'marika1234567',
                  password_confirmation: 'marika1234567',
                  name: 'Marika Tiiperi',
                  club: 'rpkk',
                  nationality: :finland
@tlf ||= User.create! email: 'teemu.lojamo@example.com',
                  password: 'teemu1234567',
                  password_confirmation: 'teemu1234567',
                  name: 'Teemu Lojamo',
                  club: 'kvks',
                  nationality: :finland
@mvf ||= User.create! email: 'maria.viitahalme@example.com',
                  password: 'maria1234567',
                  password_confirmation: 'maria1234567',
                  name: 'Maria Viitahalme',
                  club: 'kvks',
                  nationality: :finland
@mvf ||= User.create! email: 'marko.viitahalme@example.com',
                  password: 'marko1234567',
                  password_confirmation: 'marko1234567',
                  name: 'Marko Viitahalme',
                  club: 'kvks',
                  nationality: :finland
@pkf ||= User.create! email: 'petri.kiiski@example.com',
                  password: 'petri1234567',
                  password_confirmation: 'petri1234567',
                  name: 'Petri Kiiski',
                  club: 'kvks',
                  nationality: :finland
@tkf ||= User.create! email: 'teemu.kaivola@example.com',
                  password: 'teemu1234567',
                  password_confirmation: 'teemu1234567',
                  name: 'Teemu Kaivola',
                  club: 'l-svu',
                  nationality: :finland
@khf ||= User.create! email: 'kimmo.hytönen@example.com',
                  password: 'kimmo1234567',
                  password_confirmation: 'kimmo1234567',
                  name: 'Kimmo Hytönen',
                  club: 'sisuva',
                  nationality: :finland
@rkf ||= User.create! email: 'riitta.kempe@example.com',
                  password: 'riitta1234567',
                  password_confirmation: 'riitta1234567',
                  name: 'Riitta Kempe',
                  club: 'sisuva',
                  nationality: :finland
@thf ||= User.create! email: 'tiina.hakala@example.com',
                  password: 'tiina1234567',
                  password_confirmation: 'tiina1234567',
                  name: 'Tiina Hakala',
                  club: 'l-svu',
                  nationality: :finland
@amf ||= User.create! email: 'antti.mäkiaho@example.com',
                  password: 'antti1234567',
                  password_confirmation: 'antti1234567',
                  name: 'Antti Mäkiaho',
                  club: 'l-svu',
                  nationality: :finland
@paf ||= User.create! email: 'pia-lisa.alpua@example.com',
                  password: 'pia-lisa1234567',
                  password_confirmation: 'pia-lisa1234567',
                  name: 'Pia-Lisa Alpua',
                  club: 'shs',
                  nationality: :finland
@atf ||= User.create! email: 'anttoni.tolvi@example.com',
                  password: 'anttoni1234567',
                  password_confirmation: 'anttoni1234567',
                  name: 'Anttoni Tolvi',
                  club: 'l-svu',
                  nationality: :finland
@mnf ||= User.create! email: 'mikko.nurmi@example.com',
                  password: 'mikko1234567',
                  password_confirmation: 'mikko1234567',
                  name: 'Mikko Nurmi',
                  club: 'shs',
                  nationality: :finland
@phf ||= User.create! email: 'pasi.heinonen@example.com',
                  password: 'pasi1234567',
                  password_confirmation: 'pasi1234567',
                  name: 'Pasi Heinonen',
                  club: 'l-svu',
                  nationality: :finland
@vlf ||= User.create! email: 'vesa-pekka.lehtomäki@example.com',
                  password: 'vesa-pekka1234567',
                  password_confirmation: 'vesa-pekka1234567',
                  name: 'Vesa-Pekka Lehtomäki',
                  club: 'kvks',
                  nationality: :finland
@vhf ||= User.create! email: 'ville.halme@example.com',
                  password: 'ville1234567',
                  password_confirmation: 'ville1234567',
                  name: 'Ville Halme',
                  club: 'l-svu',
                  nationality: :finland
@alf ||= User.create! email: 'ari.laitinen@example.com',
                  password: 'ari1234567',
                  password_confirmation: 'ari1234567',
                  name: 'Ari Laitinen',
                  club: 'iksy',
                  nationality: :finland
@spf ||= User.create! email: 'sanna.polso@example.com',
                  password: 'sanna1234567',
                  password_confirmation: 'sanna1234567',
                  name: 'Sanna Polso',
                  club: 'sisuva',
                  nationality: :finland
@amf ||= User.create! email: 'antti.mäkiaho@example.com',
                  password: 'antti1234567',
                  password_confirmation: 'antti1234567',
                  name: 'Antti Mäkiaho',
                  club: 'l-svu',
                  nationality: :finland
@ehf ||= User.create! email: 'essi.hytönen@example.com',
                  password: 'essi1234567',
                  password_confirmation: 'essi1234567',
                  name: 'Essi Hytönen',
                  club: 'sisuva',
                  nationality: :finland
@khf ||= User.create! email: 'kimmo.hytönen@example.com',
                  password: 'kimmo1234567',
                  password_confirmation: 'kimmo1234567',
                  name: 'Kimmo Hytönen',
                  club: 'sisuva',
                  nationality: :finland
@rkf ||= User.create! email: 'riitta.kempe@example.com',
                  password: 'riitta1234567',
                  password_confirmation: 'riitta1234567',
                  name: 'Riitta Kempe',
                  club: 'sisuva',
                  nationality: :finland
@kpf ||= User.create! email: 'katariina.puolakanaho@example.com',
                  password: 'katariina1234567',
                  password_confirmation: 'katariina1234567',
                  name: 'Katariina Puolakanaho',
                  club: 'l-svu',
                  nationality: :finland
@klf ||= User.create! email: 'kaisa.lehto@example.com',
                  password: 'kaisa1234567',
                  password_confirmation: 'kaisa1234567',
                  name: 'Kaisa Lehto',
                  club: 'shs',
                  nationality: :finland
@vlf ||= User.create! email: 'vesa-pekka.lehtomäki@example.com',
                  password: 'vesa-pekka1234567',
                  password_confirmation: 'vesa-pekka1234567',
                  name: 'Vesa-Pekka Lehtomäki',
                  club: 'kvks',
                  nationality: :finland
@sbf ||= User.create! email: 'susanna.byrkland@example.com',
                  password: 'susanna1234567',
                  password_confirmation: 'susanna1234567',
                  name: 'Susanna Byrkland',
                  club: 'l-svu',
                  nationality: :finland
@apf ||= User.create! email: 'anu.parikka@example.com',
                  password: 'anu1234567',
                  password_confirmation: 'anu1234567',
                  name: 'Anu Parikka',
                  club: 'shs',
                  nationality: :finland
@jrf ||= User.create! email: 'juha.romppanen@example.com',
                  password: 'juha1234567',
                  password_confirmation: 'juha1234567',
                  name: 'Juha Romppanen',
                  club: 'shs',
                  nationality: :finland
@akf ||= User.create! email: 'anne.kiijärvi@example.com',
                  password: 'anne1234567',
                  password_confirmation: 'anne1234567',
                  name: 'Anne Kiijärvi',
                  club: 'shs',
                  nationality: :finland
@ahkf ||= User.create! email: 'agneta.henriksson.kiruna,@example.com',
                  password: 'agneta1234567',
                  password_confirmation: 'agneta1234567',
                  name: 'Agneta Henriksson Kiruna,',
                  club: 'swe',
                  nationality: :finland
@aif ||= User.create! email: 'anna-kristina.isoviita@example.com',
                  password: 'anna-kristina1234567',
                  password_confirmation: 'anna-kristina1234567',
                  name: 'Anna-Kristina Isoviita',
                  club: 'shs',
                  nationality: :finland
@taf ||= User.create! email: 'tero.asula@example.com',
                  password: 'tero1234567',
                  password_confirmation: 'tero1234567',
                  name: 'Tero Asula',
                  club: 'l-svu',
                  nationality: :finland
@vrsf ||= User.create! email: 'viktoria.ryytty.sphk,@example.com',
                  password: 'viktoria1234567',
                  password_confirmation: 'viktoria1234567',
                  name: 'Viktoria Ryytty SPHK,',
                  club: 'swe',
                  nationality: :finland
@kpf ||= User.create! email: 'kirsti.parikka@example.com',
                  password: 'kirsti1234567',
                  password_confirmation: 'kirsti1234567',
                  name: 'Kirsti Parikka',
                  club: 'shs',
                  nationality: :finland
@rsf ||= User.create! email: 'reima.saapunki@example.com',
                  password: 'reima1234567',
                  password_confirmation: 'reima1234567',
                  name: 'Reima Saapunki',
                  club: 'alma',
                  nationality: :finland
@mhf ||= User.create! email: 'mika.hamari@example.com',
                  password: 'mika1234567',
                  password_confirmation: 'mika1234567',
                  name: 'Mika Hamari',
                  club: 'alma',
                  nationality: :finland
@shf ||= User.create! email: 'sirkka-liisa.hamari@example.com',
                  password: 'sirkka-liisa1234567',
                  password_confirmation: 'sirkka-liisa1234567',
                  name: 'Sirkka-Liisa Hamari',
                  club: 'alma',
                  nationality: :finland
@nmf ||= User.create! email: 'niina.miettinen@example.com',
                  password: 'niina1234567',
                  password_confirmation: 'niina1234567',
                  name: 'Niina Miettinen',
                  club: 'alma',
                  nationality: :finland
@rsf ||= User.create! email: 'riku.setälä@example.com',
                  password: 'riku1234567',
                  password_confirmation: 'riku1234567',
                  name: 'Riku Setälä',
                  club: 'l-svu',
                  nationality: :finland
@alf ||= User.create! email: 'ari.laitinen@example.com',
                  password: 'ari1234567',
                  password_confirmation: 'ari1234567',
                  name: 'Ari Laitinen',
                  club: 'iksy',
                  nationality: :finland


###############################################################
#ec2014 skiing

@ekn ||= User.create! email: 'eskil.knag@example.com',
                  password: 'eskil1234567',
                  password_confirmation: 'eskil1234567',
                  name: 'Eskil Knag',
                  club: '',
                  nationality: :norway
@vjf ||= User.create! email: 'vesa-pekka.jurvelin@example.com',
                  password: 'vesa-pekka1234567',
                  password_confirmation: 'vesa-pekka1234567',
                  name: 'Vesa-Pekka Jurvelin',
                  club: '',
                  nationality: :finland
@yhn ||= User.create! email: 'yngve.hoel@example.com',
                  password: 'yngve1234567',
                  password_confirmation: 'yngve1234567',
                  name: 'Yngve Hoel',
                  club: '',
                  nationality: :norway
@mks ||= User.create! email: 'maurin.kerst@example.com',
                  password: 'maurin1234567',
                  password_confirmation: 'maurin1234567',
                  name: 'Maurin Kerst',
                  club: '',
                  nationality: :switzerland
@tahn ||= User.create! email: 'trond.are.hoel@example.com',
                  password: 'trond1234567',
                  password_confirmation: 'trond1234567',
                  name: 'Trond Are Hoel',
                  club: '',
                  nationality: :norway
@ams ||= User.create! email: 'adrian.meissner@example.com',
                  password: 'adrian1234567',
                  password_confirmation: 'adrian1234567',
                  name: 'Adrian Meissner',
                  club: '',
                  nationality: :switzerland
@ylf ||= User.create! email: 'yann.latrompette@example.com',
                  password: 'yann1234567',
                  password_confirmation: 'yann1234567',
                  name: 'Yann Latrompette',
                  club: '',
                  nationality: :france
@mtf ||= User.create! email: 'marko.törmänen@example.com',
                  password: 'marko1234567',
                  password_confirmation: 'marko1234567',
                  name: 'Marko Törmänen',
                  club: '',
                  nationality: :finland
@mln ||= User.create! email: 'mikael.lillestu@example.com',
                  password: 'mikael1234567',
                  password_confirmation: 'mikael1234567',
                  name: 'Mikael Lillestu',
                  club: '',
                  nationality: :norway
@vcs ||= User.create! email: 'victor.carrasco@example.com',
                  password: 'victor1234567',
                  password_confirmation: 'victor1234567',
                  name: 'Victor Carrasco',
                  club: '',
                  nationality: :spain
@mps ||= User.create! email: 'micael.pettersson@example.com',
                  password: 'micael1234567',
                  password_confirmation: 'micael1234567',
                  name: 'Micael Pettersson',
                  club: '',
                  nationality: :sweden
@lcf ||= User.create! email: 'ludovic.coulaux@example.com',
                  password: 'ludovic1234567',
                  password_confirmation: 'ludovic1234567',
                  name: 'Ludovic Coulaux',
                  club: '',
                  nationality: :france
@jps ||= User.create! email: 'jonas.persson@example.com',
                  password: 'jonas1234567',
                  password_confirmation: 'jonas1234567',
                  name: 'Jonas Persson',
                  club: '',
                  nationality: :sweden
@mvf ||= User.create! email: 'marko.viitahalme@example.com',
                  password: 'marko1234567',
                  password_confirmation: 'marko1234567',
                  name: 'Marko Viitahalme',
                  club: '',
                  nationality: :finland
@snf ||= User.create! email: 'samuli.nissinen@example.com',
                  password: 'samuli1234567',
                  password_confirmation: 'samuli1234567',
                  name: 'Samuli Nissinen',
                  club: '',
                  nationality: :finland
@kif ||= User.create! email: 'kai.immonen@example.com',
                  password: 'kai1234567',
                  password_confirmation: 'kai1234567',
                  name: 'Kai Immonen',
                  club: '',
                  nationality: :finland
@pkf ||= User.create! email: 'petri.kiiski@example.com',
                  password: 'petri1234567',
                  password_confirmation: 'petri1234567',
                  name: 'Petri Kiiski',
                  club: '',
                  nationality: :finland
@sef ||= User.create! email: 'stephane.ettwiller@example.com',
                  password: 'stephane1234567',
                  password_confirmation: 'stephane1234567',
                  name: 'Stephane Ettwiller',
                  club: '',
                  nationality: :france
@mnf ||= User.create! email: 'maija.nivala@example.com',
                  password: 'maija1234567',
                  password_confirmation: 'maija1234567',
                  name: 'Maija Nivala',
                  club: '',
                  nationality: :finland
@cann ||= User.create! email: 'carina.aas.nilsen@example.com',
                  password: 'carina1234567',
                  password_confirmation: 'carina1234567',
                  name: 'Carina Aas Nilsen',
                  club: '',
                  nationality: :norway
@mvf ||= User.create! email: 'minna.viide@example.com',
                  password: 'minna1234567',
                  password_confirmation: 'minna1234567',
                  name: 'Minna Viide',
                  club: '',
                  nationality: :finland
@mtf ||= User.create! email: 'marika.tiiperi@example.com',
                  password: 'marika1234567',
                  password_confirmation: 'marika1234567',
                  name: 'Marika Tiiperi',
                  club: '',
                  nationality: :finland
@kmf ||= User.create! email: 'kati.mansikkasalo-jurvelin@example.com',
                  password: 'kati1234567',
                  password_confirmation: 'kati1234567',
                  name: 'Kati Mansikkasalo-Jurvelin',
                  club: '',
                  nationality: :finland
@slf ||= User.create! email: 'saara.loukkola@example.com',
                  password: 'saara1234567',
                  password_confirmation: 'saara1234567',
                  name: 'Saara Loukkola',
                  club: '',
                  nationality: :finland
@tbs ||= User.create! email: 'tiina.blom@example.com',
                  password: 'tiina1234567',
                  password_confirmation: 'tiina1234567',
                  name: 'Tiina Blom',
                  club: '',
                  nationality: :sweden
@skan ||= User.create! email: 'solveig.k..aaseby@example.com',
                  password: 'solveig1234567',
                  password_confirmation: 'solveig1234567',
                  name: 'Solveig K. Aaseby',
                  club: '',
                  nationality: :norway
@ans ||= User.create! email: 'Åsa.nordgren@example.com',
                  password: 'Åsa1234567',
                  password_confirmation: 'Åsa1234567',
                  name: 'Åsa Nordgren',
                  club: '',
                  nationality: :sweden
@mvf ||= User.create! email: 'maria.viitahalme@example.com',
                  password: 'maria1234567',
                  password_confirmation: 'maria1234567',
                  name: 'Maria Viitahalme',
                  club: '',
                  nationality: :finland
@smr ||= User.create! email: 'svetlana.muravskaya@example.com',
                  password: 'svetlana1234567',
                  password_confirmation: 'svetlana1234567',
                  name: 'Svetlana Muravskaya',
                  club: '',
                  nationality: :russia
@hkf ||= User.create! email: 'heidi.kyyrönen@example.com',
                  password: 'heidi1234567',
                  password_confirmation: 'heidi1234567',
                  name: 'Heidi Kyyrönen',
                  club: '',
                  nationality: :finland
@hkf ||= User.create! email: 'hanna.kaipiainen@example.com',
                  password: 'hanna1234567',
                  password_confirmation: 'hanna1234567',
                  name: 'Hanna Kaipiainen',
                  club: '',
                  nationality: :finland
@kkf ||= User.create! email: 'kirsi.käyhty@example.com',
                  password: 'kirsi1234567',
                  password_confirmation: 'kirsi1234567',
                  name: 'Kirsi Käyhty',
                  club: '',
                  nationality: :finland
@ccf ||= User.create! email: 'corentin.coste@example.com',
                  password: 'corentin1234567',
                  password_confirmation: 'corentin1234567',
                  name: 'Corentin Coste',
                  club: '',
                  nationality: :france
@abr ||= User.create! email: 'alexei.burashov@example.com',
                  password: 'alexei1234567',
                  password_confirmation: 'alexei1234567',
                  name: 'Alexei Burashov',
                  club: '',
                  nationality: :russia
@tnf ||= User.create! email: 'tuomas.notko@example.com',
                  password: 'tuomas1234567',
                  password_confirmation: 'tuomas1234567',
                  name: 'Tuomas Notko',
                  club: '',
                  nationality: :finland
@ean ||= User.create! email: 'eira.aaseby@example.com',
                  password: 'eira1234567',
                  password_confirmation: 'eira1234567',
                  name: 'Eira Aaseby',
                  club: '',
                  nationality: :norway
@mns ||= User.create! email: 'madelene.nord@example.com',
                  password: 'madelene1234567',
                  password_confirmation: 'madelene1234567',
                  name: 'Madelene Nord',
                  club: '',
                  nationality: :sweden
@ofan ||= User.create! email: 'oda.foss.almqvist@example.com',
                  password: 'oda1234567',
                  password_confirmation: 'oda1234567',
                  name: 'Oda Foss Almqvist',
                  club: '',
                  nationality: :norway
@sns ||= User.create! email: 'sanna.näslund@example.com',
                  password: 'sanna1234567',
                  password_confirmation: 'sanna1234567',
                  name: 'Sanna Näslund',
                  club: '',
                  nationality: :sweden
@akan ||= User.create! email: 'anna.kristine.amundrud@example.com',
                  password: 'anna1234567',
                  password_confirmation: 'anna1234567',
                  name: 'Anna Kristine Amundrud',
                  club: '',
                  nationality: :norway
@jlf ||= User.create! email: 'jonna.lipponen@example.com',
                  password: 'jonna1234567',
                  password_confirmation: 'jonna1234567',
                  name: 'Jonna Lipponen',
                  club: '',
                  nationality: :finland
@tif ||= User.create! email: 'tanja.ignatius@example.com',
                  password: 'tanja1234567',
                  password_confirmation: 'tanja1234567',
                  name: 'Tanja Ignatius',
                  club: '',
                  nationality: :finland
@vif ||= User.create! email: 'vera.ignatius@example.com',
                  password: 'vera1234567',
                  password_confirmation: 'vera1234567',
                  name: 'Vera Ignatius',
                  club: '',
                  nationality: :finland
@ean ||= User.create! email: 'eira.aaseby@example.com',
                  password: 'eira1234567',
                  password_confirmation: 'eira1234567',
                  name: 'Eira Aaseby',
                  club: '',
                  nationality: :norway
@sns ||= User.create! email: 'sanna.näslund@example.com',
                  password: 'sanna1234567',
                  password_confirmation: 'sanna1234567',
                  name: 'Sanna Näslund',
                  club: '',
                  nationality: :sweden
@ofan ||= User.create! email: 'oda.foss.almqvist@example.com',
                  password: 'oda1234567',
                  password_confirmation: 'oda1234567',
                  name: 'Oda Foss Almqvist',
                  club: '',
                  nationality: :norway
@akan ||= User.create! email: 'anna.kristine.amundrud@example.com',
                  password: 'anna1234567',
                  password_confirmation: 'anna1234567',
                  name: 'Anna Kristine Amundrud',
                  club: '',
                  nationality: :norway
@mns ||= User.create! email: 'madelene.nord@example.com',
                  password: 'madelene1234567',
                  password_confirmation: 'madelene1234567',
                  name: 'Madelene Nord',
                  club: '',
                  nationality: :sweden
@cann ||= User.create! email: 'carina.aas.nilsen@example.com',
                  password: 'carina1234567',
                  password_confirmation: 'carina1234567',
                  name: 'Carina Aas Nilsen',
                  club: '',
                  nationality: :norway
@skan ||= User.create! email: 'solveig.k..aaseby@example.com',
                  password: 'solveig1234567',
                  password_confirmation: 'solveig1234567',
                  name: 'Solveig K. Aaseby',
                  club: '',
                  nationality: :norway
@mnf ||= User.create! email: 'maija.nivala@example.com',
                  password: 'maija1234567',
                  password_confirmation: 'maija1234567',
                  name: 'Maija Nivala',
                  club: '',
                  nationality: :finland
@tbs ||= User.create! email: 'tiina.blom@example.com',
                  password: 'tiina1234567',
                  password_confirmation: 'tiina1234567',
                  name: 'Tiina Blom',
                  club: '',
                  nationality: :sweden
@mtf ||= User.create! email: 'marika.tiiperi@example.com',
                  password: 'marika1234567',
                  password_confirmation: 'marika1234567',
                  name: 'Marika Tiiperi',
                  club: '',
                  nationality: :finland
@yhn ||= User.create! email: 'yngve.hoel@example.com',
                  password: 'yngve1234567',
                  password_confirmation: 'yngve1234567',
                  name: 'Yngve Hoel',
                  club: '',
                  nationality: :norway
@vjf ||= User.create! email: 'vesa-pekka.jurvelin@example.com',
                  password: 'vesa-pekka1234567',
                  password_confirmation: 'vesa-pekka1234567',
                  name: 'Vesa-Pekka Jurvelin',
                  club: '',
                  nationality: :finland
@ekn ||= User.create! email: 'eskil.knag@example.com',
                  password: 'eskil1234567',
                  password_confirmation: 'eskil1234567',
                  name: 'Eskil Knag',
                  club: '',
                  nationality: :norway
@mws ||= User.create! email: 'magnus.westerlund@example.com',
                  password: 'magnus1234567',
                  password_confirmation: 'magnus1234567',
                  name: 'Magnus Westerlund',
                  club: '',
                  nationality: :sweden
@mln ||= User.create! email: 'mikael.lillestu@example.com',
                  password: 'mikael1234567',
                  password_confirmation: 'mikael1234567',
                  name: 'Mikael Lillestu',
                  club: '',
                  nationality: :norway
@jps ||= User.create! email: 'jonas.persson@example.com',
                  password: 'jonas1234567',
                  password_confirmation: 'jonas1234567',
                  name: 'Jonas Persson',
                  club: '',
                  nationality: :sweden
@tahn ||= User.create! email: 'trond.are.hoel@example.com',
                  password: 'trond1234567',
                  password_confirmation: 'trond1234567',
                  name: 'Trond Are Hoel',
                  club: '',
                  nationality: :norway
@ylf ||= User.create! email: 'yann.latrompette@example.com',
                  password: 'yann1234567',
                  password_confirmation: 'yann1234567',
                  name: 'Yann Latrompette',
                  club: '',
                  nationality: :france
@snf ||= User.create! email: 'samuli.nissinen@example.com',
                  password: 'samuli1234567',
                  password_confirmation: 'samuli1234567',
                  name: 'Samuli Nissinen',
                  club: '',
                  nationality: :finland
@mks ||= User.create! email: 'maurin.kerst@example.com',
                  password: 'maurin1234567',
                  password_confirmation: 'maurin1234567',
                  name: 'Maurin Kerst',
                  club: '',
                  nationality: :switzerland
@lcf ||= User.create! email: 'ludovic.coulaux@example.com',
                  password: 'ludovic1234567',
                  password_confirmation: 'ludovic1234567',
                  name: 'Ludovic Coulaux',
                  club: '',
                  nationality: :france
@ams ||= User.create! email: 'adrian.meissner@example.com',
                  password: 'adrian1234567',
                  password_confirmation: 'adrian1234567',
                  name: 'Adrian Meissner',
                  club: '',
                  nationality: :switzerland
@tlf ||= User.create! email: 'teemu.lojamo@example.com',
                  password: 'teemu1234567',
                  password_confirmation: 'teemu1234567',
                  name: 'Teemu Lojamo',
                  club: '',
                  nationality: :finland
@pkf ||= User.create! email: 'petri.kiiski@example.com',
                  password: 'petri1234567',
                  password_confirmation: 'petri1234567',
                  name: 'Petri Kiiski',
                  club: '',
                  nationality: :finland

##################################################################
# roi

@vjf ||= User.create! email: 'vesa-pekka.jurvelin@example.com',
                  password: 'vesa-pekka1234567',
                  password_confirmation: 'vesa-pekka1234567',
                  name: 'Vesa-Pekka Jurvelin',
                  club: 'rpkk',
                  nationality: :finland
@mnf ||= User.create! email: 'maija.nivala@example.com',
                  password: 'maija1234567',
                  password_confirmation: 'maija1234567',
                  name: 'Maija Nivala',
                  club: 'rpkk',
                  nationality: :finland
@klf ||= User.create! email: 'kaisa.lehto@example.com',
                  password: 'kaisa1234567',
                  password_confirmation: 'kaisa1234567',
                  name: 'Kaisa Lehto',
                  club: 'kspk',
                  nationality: :finland
@klf ||= User.create! email: 'katja.lindberg@example.com',
                  password: 'katja1234567',
                  password_confirmation: 'katja1234567',
                  name: 'Katja Lindberg',
                  club: 'ce',
                  nationality: :finland
@rsf ||= User.create! email: 'reima.saapunki@example.com',
                  password: 'reima1234567',
                  password_confirmation: 'reima1234567',
                  name: 'Reima Saapunki',
                  club: 'alma',
                  nationality: :finland
@mtf ||= User.create! email: 'marika.tiiperi@example.com',
                  password: 'marika1234567',
                  password_confirmation: 'marika1234567',
                  name: 'Marika Tiiperi',
                  club: 'rpkk',
                  nationality: :finland
@mrf ||= User.create! email: 'mika.rainti@example.com',
                  password: 'mika1234567',
                  password_confirmation: 'mika1234567',
                  name: 'Mika Rainti',
                  club: 'alma',
                  nationality: :finland
@vjf ||= User.create! email: 'vesa-pekka.jurvelin@example.com',
                  password: 'vesa-pekka1234567',
                  password_confirmation: 'vesa-pekka1234567',
                  name: 'Vesa-Pekka Jurvelin',
                  club: 'rpkk',
                  nationality: :finland
@kmf ||= User.create! email: 'kati.mansikkasalo-jurvelin@example.com',
                  password: 'kati1234567',
                  password_confirmation: 'kati1234567',
                  name: 'Kati Mansikkasalo-Jurvelin',
                  club: 'rpkk',
                  nationality: :finland
@mnf ||= User.create! email: 'maija.nivala@example.com',
                  password: 'maija1234567',
                  password_confirmation: 'maija1234567',
                  name: 'Maija Nivala',
                  club: 'rpkk',
                  nationality: :finland
@nkf ||= User.create! email: 'niina.konttaniemi@example.com',
                  password: 'niina1234567',
                  password_confirmation: 'niina1234567',
                  name: 'Niina Konttaniemi',
                  club: 'rpkk',
                  nationality: :finland
@tnf ||= User.create! email: 'tuomas.notko@example.com',
                  password: 'tuomas1234567',
                  password_confirmation: 'tuomas1234567',
                  name: 'Tuomas Notko',
                  club: 'rpkk',
                  nationality: :finland
@tnf ||= User.create! email: 'tuomas.notko@example.com',
                  password: 'tuomas1234567',
                  password_confirmation: 'tuomas1234567',
                  name: 'Tuomas Notko',
                  club: 'rpkk',
                  nationality: :finland
@tnf ||= User.create! email: 'tuomas.notko@example.com',
                  password: 'tuomas1234567',
                  password_confirmation: 'tuomas1234567',
                  name: 'Tuomas Notko',
                  club: 'rpkk',
                  nationality: :finland
@eÄf ||= User.create! email: 'eeva.Äijälä@example.com',
                  password: 'eeva1234567',
                  password_confirmation: 'eeva1234567',
                  name: 'Eeva Äijälä',
                  club: 'avek',
                  nationality: :finland
@aaf ||= User.create! email: 'anu.ailinpieti@example.com',
                  password: 'anu1234567',
                  password_confirmation: 'anu1234567',
                  name: 'Anu Ailinpieti',
                  club: 'kspk',
                  nationality: :finland
@klf ||= User.create! email: 'kaisa.lehto@example.com',
                  password: 'kaisa1234567',
                  password_confirmation: 'kaisa1234567',
                  name: 'Kaisa Lehto',
                  club: 'kspk',
                  nationality: :finland
@rsf ||= User.create! email: 'reima.saapunki@example.com',
                  password: 'reima1234567',
                  password_confirmation: 'reima1234567',
                  name: 'Reima Saapunki',
                  club: 'alma',
                  nationality: :finland
@hkf ||= User.create! email: 'heidi.kyyrönen@example.com',
                  password: 'heidi1234567',
                  password_confirmation: 'heidi1234567',
                  name: 'Heidi Kyyrönen',
                  club: 'rpkk',
                  nationality: :finland
@mtf ||= User.create! email: 'marika.tiiperi@example.com',
                  password: 'marika1234567',
                  password_confirmation: 'marika1234567',
                  name: 'Marika Tiiperi',
                  club: 'rpkk',
                  nationality: :finland
@ahf ||= User.create! email: 'anna.heinonen@example.com',
                  password: 'anna1234567',
                  password_confirmation: 'anna1234567',
                  name: 'Anna Heinonen',
                  club: 'rpkk',
                  nationality: :finland
